### ISSUE TITLE
Telltail CLI doesn't detect AutoHotkey (auto hot key, AHK)

### ISSUE THREAD

**Issue by darrenwjlau** [ajitid/telltail-sync#2]

**Comment by ajitid** [comment]
I would need more info to resolve this for you. Have you installed AutoHotkey (AHK) or have you just unzipped its content somewhere? And if you have installed me, could you tell me what is the process you took (used installer from website, used scoop, chocolatey, winget or something else)?

**Comment by ajitid** [comment]
I've updated the CLI to properly detect AutoHotkey. Delete the CLI that you've downloaded and re-download it from [the webpage](https://guide-on.gitbook.io/telltail/installation/setup-telltail-center). Should work this time around.

**Comment by ajitid** [comment]
@mickeydarrenlau, did you get a chance to look at it? (re: see my comment right above)

**Comment by ajitid** [comment]
Closing the ticket for now. If the issue appears again, we can reopen it.
